### PR TITLE
Allow to set "service links" during create.

### PR DESCRIPTION
**Pull request by mrpolman**

### CODE REVIEW

**Comment by cdrx** [comment]
Thank you @mrpolman

**Comment by R4wizard** [comment]
After spending a little while investigating why our build deployments failed. We came to the conclusion that within this merge request are some strange unicode bytes in the `rancher_gitlab_deploy/cli.py` file.

You can see an example of this here: https://i.imgur.com/tT2YhWP.png

This then appears to be causing the following error upon execution:

```
Traceback (most recent call last):
  File "/usr/local/bin/upgrade", line 11, in <module>
    load_entry_point('rancher-gitlab-deploy==1.5', 'console_scripts', 'rancher-gitlab-deploy')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/rancher_gitlab_deploy-1.5-py2.7.egg/rancher_gitlab_deploy/cli.py", line 243
SyntaxError: Non-ASCII character '\xe2' in file /usr/local/lib/python2.7/site-packages/rancher_gitlab_deploy-1.5-py2.7.egg/rancher_gitlab_deploy/cli.py on line 243, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by R4wizard** [comment]
It appears the only instances of this are on line 243 and line 261.

**Comment by cdrx** [comment]
@R4wizard thank you -- I'm just about to push a fix out to dockerhub

**Comment by mrpolman** [comment]
@R4wizard It is fixed here https://github.com/cdrx/rancher-gitlab-deploy/pull/60

**Comment by cdrx** [comment]
Fix now deployed on Docker Hub, @R4wizard your builds should work again

**Comment by mrpolman** [comment]
@R4wizard @cdrx Sorry for this, I have no idea how this "character" got there.

**Comment by cdrx** [comment]
No worries

I will take the time soon to setup travis or circle ci and get it to test the code before its merged

**Comment by R4wizard** [comment]
@mrpolman These unicode chars get us all at some point! 
@cdrx Thanks for the quick fix on this. CI testing is the way forward!

**Pull request merged**
