### PR TITLE
Allow environment variables to be created with the service

### PR DESCRIPTION
**Pull request by mleczakm**
Allows to set environment variables on created sevices.

### CODE REVIEW

**Comment by mleczakm** [comment]
i think it would be nice to release new version of service, since tag 1.5 on hub is really old :)

**Comment by cdrx** [comment]
@mleczakm thank you for this PR -- could you please fix the conflicts, and I'll merge? 

I would like to release version 1.6 and it would be good to get this feature in, if possible.

**Comment by mleczakm** [comment]
@cdrx In fact I am not sure if this should be merged, since it should be possible for env variables to have `,` inside - I was thinking about rewriting it (and probably  also already merged labels) to accept multiple inputs like `-env name=value -env another_name=value` etc. - what do you think about it?

**Comment by cdrx** [comment]
Yes, I think that would be much cleaner. Click has support for multi value options which would make it simple enough to implement without the `=`

I think adding a `—label` option would be great too, but we should keep the existing `—labels` option so we don’t break existing deployments :)

**Comment by tsteenkamp** [comment]
Hey @cdrx , @mleczakm ,

any progress on this feature? At my company we are in dire need of the -env feature and if it will be merged or released with the 1.6 version in the next couple of days we could avoid forking and having to implement it ourselves. Please let me know if I can help with implementing or testing it! Thanks!

**Comment by cdrx** [comment]
If there was progress on this feature it would be posted here. If you are in urgent need of the feature I suggest implementing it yourself -- feel free to submit a PR and I will gladly merge it.

**Comment by cdrx** [comment]
Has been implemented in #56, closing this one now

**Pull request closed without merging**
